
$('#phi').text(degrees((controls.getPolarAngle())).toFixed(dec))
$('#theta').text(degrees((controls.getAzimuthalAngle())).toFixed(dec))
$('#controlsPositionX').text(controls.object.position.x.toFixed(dec))
$('#controlsPositionY').text(controls.object.position.y.toFixed(dec))
$('#controlsPositionZ').text(controls.object.position.z.toFixed(dec))
$('#controlsRotationX').text(controls.object.rotation.x.toFixed(dec))
$('#controlsRotationY').text(controls.object.rotation.y.toFixed(dec))
$('#controlsRotationZ').text(controls.object.rotation.z.toFixed(dec))

$('#cameraPositionX').text(camera.position.x.toFixed(dec))
$('#cameraPositionY').text(camera.position.y.toFixed(dec))
$('#cameraPositionZ').text(camera.position.z.toFixed(dec))
$('#cameraRotationX').text(camera.rotation.x.toFixed(dec))
$('#cameraRotationY').text(camera.rotation.y.toFixed(dec))
$('#cameraRotationZ').text(camera.rotation.z.toFixed(dec))

$('#scenePositionX').text(scene.position.x.toFixed(dec))
$('#scenePositionY').text(scene.position.y.toFixed(dec))
$('#scenePositionZ').text(scene.position.z.toFixed(dec))
$('#sceneRotationX').text(scene.rotation.x.toFixed(dec))
$('#sceneRotationY').text(scene.rotation.y.toFixed(dec))
$('#sceneRotationZ').text(scene.rotation.z.toFixed(dec))